# Generated by Django 5.1.4 on 2024-12-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0002_alter_promocion_puede_tener_promociones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.IntegerField(null=True, verbose_name='4'),
        ),
    ]
