# Generated by Django 5.1.4 on 2024-12-12 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0003_alter_promocion_descuento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promocion',
            name='Descripción',
        ),
        migrations.AddField(
            model_name='promocion',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='descuento',
            field=models.IntegerField(null=True),
        ),
    ]
